### ISSUE TITLE
Let Object Explorer move outside VFP

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/ObjectExplorer#41]
## 📝 Provide a description of the new feature

It would be very handy to be able to move Object Explorer outside the VFP window, so that it doesn't cover the form you're looking at. Please make it (optionally) a top-level form.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
@TamarEGranor 

Currently, it's behavior is modal.  

Making it a top-level form changes that and wonder if it matters

I am not sure of the implications; thus, before releasing it in the wild, since I do not have an easy way to test this, I request you try modifying it yourself:

`Modify Form (_Screen.cThorFolder + 'Tools\Apps\Object Explorer\Explorer')`

If it works properly for you when a top level form, I'll provide an option.

(I wonder about what happens if you close the source form first or try to open a second form).

**Comment by TamarEGranor** [comment]
Just tried it and it looks fine to me. I'm going to leave it that way as I continue testing it out.

**Comment by Jimrnelson** [comment]
Good to hear.  

I hope to have an option available to handle this by the weekend (especially if I can solve the other item you raised, #40.

**Comment by Jimrnelson** [comment]
Fixed in today's release 3.4.02
